
#!/bin/bash
cd ..

set -euo pipefail
SDKCONFIG="${1:-sdkconfig}"

CONFIG_IDF_TARGET=$(grep -E '^CONFIG_IDF_TARGET=' "$SDKCONFIG" | sed -E 's/^CONFIG_IDF_TARGET="([^"]+)".*/\1/')
CONFIG_ESPTOOLPY_FLASHSIZE=$(grep -E '^CONFIG_ESPTOOLPY_FLASHSIZE=' "$SDKCONFIG" | sed -E 's/^CONFIG_ESPTOOLPY_FLASHSIZE="([^"]+)".*/\1/')
CONFIG_ESPTOOLPY_FLASHFREQ=$(grep -E '^CONFIG_ESPTOOLPY_FLASHFREQ=' "$SDKCONFIG" | sed -E 's/^CONFIG_ESPTOOLPY_FLASHFREQ="([^"]+)".*/\1/')
CONFIG_ESPTOOLPY_FLASHMODE=$(grep -E '^CONFIG_ESPTOOLPY_FLASHMODE=' "$SDKCONFIG" | sed -E 's/^CONFIG_ESPTOOLPY_FLASHMODE="([^"]+)".*/\1/')
